### ISSUE TITLE
Unicode support / "Umlaute"

### ISSUE THREAD

**Issue by JayVii** [itprojects/InboxPager#11]
This issue doesn't really affect usability, it's more cosmetic. As you can see in the screenshot below (I masked everything irrelevant and underlined the issue-spots with red) "Umlaute" from the german language aren't respected properly neither in the mails themselves, nor in the Inboxname. It does work fine in the "Send Message" section.
![inboxpager_screenshot](https://user-images.githubusercontent.com/28513043/31412972-837cc55e-ae17-11e7-91a9-11282bb5cb01.png)
affected are **ü** and **ä** as far as I can see, probably **ö** and maybe **ß** as well. I suspect the fonts used here do not support these characters?

This really doesn't have high priority, I just wanted to address it and let you know about it

**Comment by itprojects** [comment]
Thank you for the bug report!
For the title bar:
Other languages are also affected, the font used has a very limited character set.

For the List View:
Maybe a change from the windows (CP-????) encoding to UTF-8 is necessary.

No fix is planned, due to time.

**Comment by itprojects** [comment]
Can you check that this is still an issue for v2.2 ?
If yes, can you provide a redacted email (removing your account name & other private information)?
When you download an email (from a desktop interface) to file, what do you see in the "subject:" line?

**Comment by itprojects** [comment]
Possibly fixed in version 3.0.
