### ISSUE TITLE
Inbox pager app gets crashed.

### ISSUE THREAD

**Issue by Sammaz2** [itprojects/InboxPager#13]
### Actual behavior
When i opened the app after that I clicked on the options present on the top right corner. After that I clicked on account to add an account. And then there I filled the given blanks. After that I filled the IMAP and SMTP blanks. And saved it. After that I tried to edit the IMAP. And then I clicked on save, but unfortunately the app suddenly crashes.

### How to reproduce

* First you need to download the app from fdroid and install it. Open the app.

* Click on the options present on the top right corner.

* Then click on account to add an account.

* After that fill all the blanks. And save it.

* Get back and then try to edit the IMAP.

* And click on save. But unfortunately the app will crash suddenly.

https://youtu.be/vcDLOsO-iMQ 

* Browser: Inbox pager

* Version:2.2

* Operating system:7.1.2

* Device model: Redmi 4.

**Comment by itprojects** [comment]
Fixed in version 3.0.
