### ISSUE TITLE
Inbox pager app gets crashed.

### ISSUE THREAD

**Issue by Sammaz2** [itprojects/InboxPager#15]
### Actual behavior
I opened the inbox pager opensource android app. After that I clicked on the options present on the top right corner of the page. And then I clicked on account option to add an account. After that I filled the given details. And then i clicked on back button to get to the homescreen of the app and then I clicked on the saved account. After that I clicked on the options present on the top right corner. I opened the settings. And then I clicked on try incoming, app suddenly crashed. And even when i clicked on try outgoing, same was the case with that, app crashed.

### How to reproduce

* First you need to download the app from fdroid and then install it. After that open the app.

* Click on the options present on the top right corner of the page.

* Click on the account option to add an account.

* Fill the given details.

* And then save it.

* After that click on the saved account name. And then click on the option present on the top right corner. Open the settings.

* Then click on try incoming option. Suddenly the app will crash.

* Or you can also click on try outgoing, same is the case with that. App crashes suddenly.

https://youtu.be/Pjnm-ZwJZmc 

* Browser: Inbox pager.

* Version:2.2

* Operating system:7.1.2

* Device model:Redmi 4

**Comment by itprojects** [comment]
Thank you for the video.

The app can work without these test, if the correct port/server settings (i.e. 993 imap.gmail.com) are input. The test tools should not be crashing. This is a bug.

**Comment by itprojects** [comment]
Solved in version 3.0.
