### ISSUE TITLE
App crashes while deleting account in landscape mode. 

### ISSUE THREAD

**Issue by Xeeshuu** [itprojects/InboxPager#16]
### Actual behavior 
I had downloaded this app soo far and today i made an account in it. After that i opened it and want to delete the account which i had made before. 
After clicking the account and then rotated the to landscape mode in the settings of the account in this app. When i clicked on delete option mentioned on the top of the page in landscape mode. The app suddenly crashes. 

### How to reproduce 
Download the app from f droid. 
Make an account in it. 
After that open the account by just clickinh on it. 
On the top right corner of the page click on 3 dots. 
Here appears setting option click on it to open.
Rotate the phone to landscape mode. 
After that click on delete option.
Unfortunately the app will crash. 

* Browser: Inbox pager. 
* Version:2.2
* Operating system :5.1.1

**Comment by Xeeshuu** [comment]
Thanku

**Comment by itprojects** [comment]
Deletion happens even if app crashes. Deletion without crash if entering settings from landscape. Bug supposedly related to SQL.

**Comment by Xeeshuu** [comment]
Ok

**Comment by itprojects** [comment]
It turns out SQL is only partly at fault. The flaw seems to be the total absence of save-restore state handling. Version 3.0 (soon) should fix the crash part, the logged error message may remain.
