### ISSUE TITLE
Unable to add any attachments to messages 

### ISSUE THREAD

**Issue by Olamatto** [itprojects/InboxPager#17]
#### Expected behavior
The attachment ought to be used in adding documents, images or any attachment to the mail.

#### Actual Behavior 
After clicking on the add attachment, all fies becomes unable to be attached to the message. 

#### How to reproduce
- Download and install the application [here](https://f-droid.org/repository/browse/?fdfilter=inbox&fdid=net.inbox.pager)
- Lunch the application 
- Click on the option by the right hand corner 
- Select Add account
- Fill in all necessary details about the account
- Then click save
- Select the account
- Click on the option in the right hand corner 
- Select send message 
- Fill in all necessary details 
- Click on the Add attachment 

And see that is impossible to add attachment to message. 
<hr>

Application version: 2.2
Operating system: Android v7.0

#### Recording Of The Bug
https://youtu.be/6F0yJ6t4uOM

**Comment by itprojects** [comment]
Adding an attachment is possible using OI File Manager, but not all managers, it appears. Even if all apps have SDCard read/write permissions granted. Can you test & confirm attachment send with OI File Manager?

**Comment by Olamatto** [comment]
Yes it works with ol file manager, but i would prefer getting direct attachment.

**Comment by itprojects** [comment]
Making an internal file picker feature is one possibility.
Until then other file managers will have to be used.

**Comment by Olamatto** [comment]
Oh ok that good then, looking forward to add that feature.

**Comment by itprojects** [comment]
Fixed in 4.0, with the introduction of all-internal File Manager (Send/Save Attachments).
To be precise : 194 days. :-)
