### ISSUE TITLE
Translation pt-br

### ISSUE THREAD

**Issue by hanelore** [itprojects/InboxPager#20]
Hi.

What would be the best way to start the translation?

Thanks.

**Comment by jpereira** [comment]
@hanelore do you speak pt-br?

**Comment by hanelore** [comment]
@jpereira Yes, I learned with my partner.

Obrigada.

**Comment by jpereira** [comment]
Great! Let me know if need some help with that translation to pt-br.

**Comment by itprojects** [comment]
How to translate an Andorid app:

This file has the English original "texts":

https://github.com/itprojects/InboxPager/blob/master/InboxPager/src/main/res/values/strings.xml

This is one of the available translations.

https://github.com/itprojects/InboxPager/blob/master/InboxPager/src/main/res/values-bg/strings.xml

If you want to make another translation, it will be necessary to compile a file just like that second one, only in Portuguese/Brazilian.

You can use the Android Studio to do this very quickly!

Then you need to share this file in this form. If the file is approved, it may (or may not) become an official translation eventually (after it is noticed), but there are no guarantees or promises.

ALL TRANSLATORS ARE RESPONSIBLE FOR THE CONTENT THEY PRODUCE!

**Comment by hanelore** [comment]
Thanks @itprojects [PR sent](https://github.com/itprojects/InboxPager/pull/21).

**Comment by itprojects** [comment]
Translation is being verified. Translator Accreditation?

**Comment by itprojects** [comment]
The translation changes have been integrated into v3.1.
