### ISSUE TITLE
Filter by contact

### ISSUE THREAD

**Issue by zecamigo** [itprojects/InboxPager#25]
First of all the app looks amazing and I'll definitely be following it. Congrats!

I would love if it was possible to filter messages only from selected contacts. There is another FOSS app - Delta chat - that does that, but it has a number of other issues that make it not a choice for me.

I was hoping inbox pager would fill in the gap! Any way kudos and keep up the good work!

**Comment by itprojects** [comment]
Thank you for using the Inbox Pager e-mail client!

Sorting messages by contact/mailbox (i.e. name@server.com) is a feature that is already marked for development. There is no special deployment time frame for it, but possibly in less than a year. The efficiency of sorting is an issue.

**Comment by zecamigo** [comment]
Cool, will keep an eye out for developments. Thanks for being awesome!

**Comment by itprojects** [comment]
Sender-based expandable list view, has replaced the default, in v4.1.
