### ISSUE TITLE
[BUG] Inbox Pager crash on deleting messages

### ISSUE THREAD

**Issue by 0xlne** [itprojects/InboxPager#27]
Inbox Pager (v4.2) crashes on deleting messages from server.
It's a behaviour I could notice already on the 4.1x test versions used in troubleshooting #26.
The notification gets to the point of displaying "message deleted" but then IP crashes.
I tried this with mails from different senders, with the same result. It's always repeatable.
I'll try to get a logcat later.

Device:
Samsung Galaxy Note 10+/Android 9 (September patch).

**Comment by itprojects** [comment]
Are the messages moved to Trash in inbox (or completely deleted)?

**Comment by 0xlne** [comment]
Completely deleted.

**Comment by itprojects** [comment]
> Completely deleted.
Is the expected behaviour.

Could not replicate the error.
Did you reinstall the app from the official repository 4.2, or do you still have the old test build (github)?

If the app crashes entirely, it should be visible in logcat.

**Comment by 0xlne** [comment]
I was initially using the v4.14, but clean installed the v4.2 you pushed to f-droid. Same on both.
I will grab a logcat as soon as I can.

**Comment by 0xlne** [comment]
10-08 01:07:13.383 16580 16580 D ViewRootImpl@723f69a[?]: dispatchDetachedFromWindow
10-08 01:07:13.384  6003  9866 I WindowManager: Cancelling animation restarting=false, leash=null, surface=Surface(name=AppWindowToken{3efe205 token=Token{a33697c ActivityRecord{731186f u0 net.inbox.pager/net.inbox.InboxMessage t2865}}})/@0x78da667, parent=Surface(name=Task=2865)/@0x5705b97
10-08 01:07:13.384  6003  9866 V WindowManager: Remove Window{388a60a u0 ?}: mSurfaceController=null mAnimatingExit=false mRemoveOnExit=false mHasSurface=false surfaceShowing=false isAnimationSet=false app-animation=false mWillReplaceWindow=false inPendingTransaction=false mDisplayFrozen=false callers=com.android.server.wm.WindowState.removeIfPossible:2803 com.android.server.wm.WindowToken.removeAllWindowsIfPossible:150 com.android.server.wm.AppWindowToken.removeIfPossible:769 com.android.server.wm.AppWindowToken.onRemovedFromDisplay:845 com.android.server.wm.DisplayContent.removeAppToken:1097 com.android.server.wm.AppWindowContainerController.removeContainer:305
10-08 01:07:13.386  6003  9866 I WindowManager: commitFinishDrawingLocked: mDrawState=READY_TO_SHOW Surface(name=NavigationBar[6582])/@0x1df3ebf
10-08 01:07:13.386  5478  5478 I Layer   : id=19877 onRemoved 60ba168 net.inbox.pager/net.inbox.InboxMessage#0
10-08 01:07:13.387  5478  5846 I SurfaceFlinger: id=19881 Removed 388a60a ?#0 (0/116)
10-08 01:07:13.388  6003  9866 D InputTransport: Input channel destroyed: fd=577
10-08 01:07:13.389  6003  7004 W WindowManager: Failed looking up window callers=com.android.server.wm.WindowManagerService.windowForClientLocked:6479 com.android.server.wm.WindowManagerService.removeWindow:1950 com.android.server.wm.Session.remove:274
10-08 01:07:13.389 16580 16580 D InputTransport: Input channel destroyed: fd=77
10-08 01:07:13.390  5478  5846 I SurfaceFlinger: id=19876 Removed AppWindowToken{3efe205 token=Token{a33697c ActivityRecord{731186f u0 net.inbox.pager/net.inbox.InboxMessage t2865}}}#0 (1/115)
10-08 01:07:13.403  5478  5478 I Layer   : id=19881 onRemoved 388a60a ?#0
10-08 01:07:13.403  5478  5478 I Layer   : id=19876 onRemoved AppWindowToken{3efe205 token=Token{a33697c ActivityRecord{731186f u0 net.inbox.pager/net.inbox.InboxMessage t2865}}}#0
10-08 01:07:13.560  6003  6012 I system_server: NativeAlloc concurrent copying GC freed 138834(5MB) AllocSpace objects, 12(432KB) LOS objects, 26% free, 66MB/90MB, paused 242us total 151.094ms
10-08 01:07:13.589 16580 16580 D AndroidRuntime: Shutting down VM
10-08 01:07:13.589 16580 16580 E AndroidRuntime: FATAL EXCEPTION: main
10-08 01:07:13.589 16580 16580 E AndroidRuntime: Process: net.inbox.pager, PID: 16580
10-08 01:07:13.589 16580 16580 E AndroidRuntime: java.lang.IllegalArgumentException: View=DecorView@48f1bcb[Deleting…] not attached to window manager
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:534)
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:434)
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at android.app.Dialog.dismissDialog(Dialog.java:518)
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at android.app.Dialog.dismiss(Dialog.java:501)
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at net.inbox.dialogs.SpinningStatus.onPostExecute(SpinningStatus.java:112)
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at net.inbox.dialogs.SpinningStatus.onPostExecute(SpinningStatus.java:29)
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:695)
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at android.os.AsyncTask.access$600(AsyncTask.java:180)
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:216)
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7263)
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
10-08 01:07:13.589 16580 16580 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
10-08 01:07:13.595  6003  9866 D Debug   : !@DumpState : SHIP
10-08 01:07:13.596  6003  9866 D Debug   : !@DumpState : debug level:0x4f4c
10-08 01:07:13.596  6003  9866 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
10-08 01:07:13.596  6003  9866 W ActivityManager: crash : net.inbox.pager,0
10-08 01:07:13.599  6003  9866 W ActivityManager:   Force finishing activity net.inbox.pager/net.inbox.InboxPager



10-08 01:07:13.728  5946  5946 I CapsuleProvider_1.0.9: onCreate
10-08 01:07:13.729  5946  5946 I CapsuleProvider_1.0.9: releasing initialize wait lock.
10-08 01:07:13.730  5946  5946 I SmSettingSearchProvider: version : 1050000030, lang : en_GB
10-08 01:07:13.738  4583  4583 D ScrollView:  onsize change changed
10-08 01:07:13.739  5946  5946 I clear_sdk: [gn] setOption scan_opti_1:1
10-08 01:07:13.741  5946  5946 I clear_sdk: [gn] setOption use_sdk_delete:0
10-08 01:07:13.747  6003  6165 W InputDispatcher: channel '50de352 net.inbox.pager/net.inbox.InboxPager (server)' ~ Consumer closed input channel or an error occurred.  events=0x9, fd=660
10-08 01:07:13.747  6003  6165 E InputDispatcher: channel '50de352 net.inbox.pager/net.inbox.InboxPager (server)' ~ Channel is unrecoverably broken and will be disposed!
10-08 01:07:13.751  6003  9871 I WindowManager: WIN DEATH: Window{50de352 u0 net.inbox.pager/net.inbox.InboxPager}

**Comment by itprojects** [comment]
This bug starts with SpinningStatus.java:112 `pd.dismiss();` , and ends in an exception: java.lang.IllegalArgumentException, not attached to window manager.

One idea is that the `pd` is already null, but that should give a different exception.

Does this happen on non-gmail acounts?

**Comment by 0xlne** [comment]
I haven't tested on non-gmail accounts as I have none, but I did reinstall Inbox Pager 4.2 from scratch on the 2nd device: Xperia XZ2/stock Android 9, & the result is the same: crash on each message deleted from server.

**Comment by itprojects** [comment]
Try [build 421](https://github.com/itprojects/InboxPager/blob/apk-debug/InboxPager-421.apk). It checks for nulls and visibility. Ignore testing for non-gmails, for this bug.

**Comment by 0xlne** [comment]
https://i.postimg.cc/9MWnTvGn/Screenshot-20191010-065233-Fennec-F-Droid.jpg

**Comment by 0xlne** [comment]
I can confirm build 422 works - deleting works, with no crashes or exceptions.
Thank you for taking the time in troubleshooting ;]
