### ISSUE TITLE
[Bug] Delete from server doesn't move Gmail message to trash

### ISSUE THREAD

**Issue by esmoak** [itprojects/InboxPager#28]
4.3.12 from F-Droid appears to archive the message instead of delete when delete from server is selected. I'm not sure if this is a wontfix or a bug.

Thanks.

**Comment by itprojects** [comment]
Very likely. See the FAQ.

**Comment by esmoak** [comment]
Thanks, I didn't see a FAQ linked in the readme, but closing the issue since it's tagged as wontfix.

I approve the app. Best regards.

**Comment by esmoak** [comment]
Stumbled on the solution. This is definitely a Gmail issue and not an app issue, so posting to help others:

1) go to Gmail imap settings
2) turn auto expunge off 
3) select the option to move to trash when client updates the server.

This next step might not be necessary, but I had to enable for gmail to delete correctly with another imap program:

4) go to labels settings
5) remove check mark for showing “All Mail” in imap

Now Gmail will actually move an item to the trash instead of All Mail/Archive when an app requests an expunge.

**Comment by itprojects** [comment]
Thanks @esmoak !
