### ISSUE TITLE
[BUG] Crash on Android 10

### ISSUE THREAD

**Issue by 0xlne** [itprojects/InboxPager#32]
Inbox Pager v4.3.12 crashes on Samsung Galaxy Note 10+, Android 10.

It runs fine when initiated from scratch, adding a new account, syncing, but then fails to display inbox/messages.
Log available on https://privatebin.net/?1b77f798301d5ba6#HpYTD9Ra3ceou3nYj1VwroMEhZR6mbmPkP9Lh26oiYfL

& here:
01-31 15:24:33.744 21807 21807 D AndroidRuntime: Shutting down VM
01-31 15:24:33.744 21807 21807 E AndroidRuntime: FATAL EXCEPTION: main
01-31 15:24:33.744 21807 21807 E AndroidRuntime: Process: net.inbox.pager, PID: 21807
01-31 15:24:33.744 21807 21807 E AndroidRuntime: java.lang.NullPointerException
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at java.util.TreeMap.getEntry(TreeMap.java:348)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at java.util.TreeMap.containsKey(TreeMap.java:233)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at net.inbox.db.DBAccess.get_all_messages(DBAccess.java:604)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at net.inbox.InboxPager.populate_messages_list_view(InboxPager.java:638)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at net.inbox.InboxPager.set_current_inbox(InboxPager.java:611)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at net.inbox.InboxPager.activity_load(InboxPager.java:500)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at net.inbox.InboxPager.access$000(InboxPager.java:71)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at net.inbox.InboxPager$2.onAnimationEnd(InboxPager.java:189)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1111)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1242)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1484)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:722)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
01-31 15:24:33.744 21807 21807 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-31 15:24:33.748  5966 21847 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
01-31 15:24:33.749  5966 11367 W ActivityTaskManager:   Force finishing activity net.inbox.pager/net.inbox.InboxPager
01-31 15:24:33.756  5966  9962 I mali_winsys: new_window_surface() [1440x3040] return: 0x3000
01-31 15:24:33.756  5966  9962 E BufferQueueProducer: [unnamed-5966-27] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
01-31 15:24:33.756  5966  9962 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
01-31 15:24:33.763  5966  9962 I mali_egl: eglDestroySurface() in
01-31 15:24:33.764  5966  9962 I mali_winsys: delete_surface() [1440x3040] return
01-31 15:24:33.764  5966  9962 I mali_egl: eglDestroySurface() out
01-31 15:24:33.764  5966  9962 E BufferQueueProducer: [unnamed-5966-27] disconnect: not connected (req=1)
01-31 15:24:33.764  5966  9962 W libEGL  : EGLNativeWindowType 0x7ef56eed90 disconnect failed
01-31 15:24:33.772  5966  5994 I ActivityManager: Showing crash dialog for package net.inbox.pager u0
01-31 15:24:33.772  5966  5994 E system_server: Invalid ID 0x00000000.
01-31 15:24:33.773  5966  6002 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
01-31 15:24:33.773  5966  6002 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
01-31 15:24:33.834  5966  9962 I mali_winsys: new_window_surface() [1305x625] return: 0x3000
01-31 15:24:34.251  5966  5996 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{b280070 u0 net.inbox.pager/net.inbox.InboxPager t288 f}
01-31 15:24:34.266  5966  5996 W ActivityTaskManager: Activity pause timeout for ActivityRecord{b280070 u0 net.inbox.pager/net.inbox.InboxPager t288 f}
01-31 15:24:34.336 21678 21707 I mali_winsys: new_window_surface() [1440x2926] return: 0x3000

**Comment by itprojects** [comment]
@0xlne Can you offer steps to reproduce; from a cleanly installed app?

[Note: One reason for the non-displayed messages is because the user is supposed to click again on the account name, from the side-panel. This is a bug, but probably not related to this discussion.]

As you can see from your log below, the problem is a NullPointerException

(DBAccess.java:604) `if (messages.containsKey(current.get_from()))`

Something is missing about that message. Possibly not saved to database.

Try the following:
1. Delete account
2. Close app
3. Open app
4. Re-create account
5. Close app
6. Open app
7. Select account from side menu
8. Press refresh
9. Wait for the messages to download.
10. Select account from side menu

: Shutting down VM

: FATAL EXCEPTION: main

: Process: net.inbox.pager, PID: 21807

: java.lang.NullPointerException<-------------------------------------

: at java.util.TreeMap.getEntry(TreeMap.java:348)

: at java.util.TreeMap.containsKey(TreeMap.java:233)

: at net.inbox.db.DBAccess.get_all_messages(DBAccess.java:604)

**Comment by 0xlne** [comment]
Thank you for taking the time to look through the logs & identify the probable cause.
I have reinstalled from scratch & was unable to reproduce this issue since.
