### ISSUE TITLE
Crash I found.

### ISSUE THREAD

**Issue by SonnyADR** [itprojects/InboxPager#37]
HI  

java.lang.NoSuchMethodError: No static method encodeHexString([B)Ljava/lang/String; i

I found a defect in class DigestUtils,  

Pre - import org.apache.commons.codec.binary.Hex;  
Should -  import org.bouncycastle.util.encoders.Hex;

And replace the Hex,encodeHexString method to encodeHex

**Comment by itprojects** [comment]
Under what circumstances does this error appear?

If there is an error in "import org.apache.commons.codec.binary.Hex", you should declare it to that Apache Commons website.

BouncyCastle will not be implemented. It is a problematic package for Android.

**Comment by itprojects** [comment]
Since it is not possible to reproduce this bug, this issue will be closed.
