### ISSUE TITLE
[FEATURE REQUEST] Management of new mails

### ISSUE THREAD

**Issue by 0xlne** [itprojects/InboxPager#38]
Problem Statement:
Managing new/incoming mails is painful - especially if you need to scroll a long list. More so, when you need to restart from the top of the list after each operation on any mail.

Proposed Solution:
Enable a filter to show only unread/new mails, or at least the ability to sort by time (descending).

**Comment by itprojects** [comment]
@0xlne  New messages downloaded from the email server should appear near the top, just below the thread title. Is that the case with your inbox?

To implement a timestap filter, InboxPager needs to parse the datetime field/line, for every message. There is some code for that, but older servers have different formats (hence undefined timestamps). Also, the algorithm for sorting, may be costly for users with larger inboxes. It's an issue.

Implementing an unread filter can be a fix.

**Comment by itprojects** [comment]
@0xlne Focus mode for unread messages is available in v6.2.
