### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [itprojects/InboxPager#39]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by itprojects** [comment]
@mondlicht-und-sterne Yes, it's a known issue. Adding application screenshots was supposed to happen automatically, after the (then) next version was tagged for release.

**Comment by mondlicht-und-sterne** [comment]
ok i just went through the ones that don't show one. thank you very much.

**Comment by itprojects** [comment]
@mondlicht-und-sterne Thank you for the feedback. An issue has been opened with F-droid.

**Comment by itprojects** [comment]
@mondlicht-und-sterne F-droid app should now show the screenshots.

The F-droid may take slightly longer, but eventually is expected to also display them.
