### ISSUE TITLE
german localization "Erfrischend"

### ISSUE THREAD

**Issue by agschaid** [itprojects/InboxPager#40]
hi

I think you might have a little issue with your German localization:

I am doing my first refreshing with inital data sync. The splash screen with the spinner says "erfrischend". Now this does translate to "refreshing" but to the adjective (as in "I find this App very refreshing"). [reference](https://dict.leo.org/german-english/erfrischend)

I guess what you want is the verb (as in "I am refreshing your mail data") and here the correct joice would be "aktualisiere". [reference](https://dict.leo.org/german-english/aktualisiere)

So my suggestion:
in your German localization file replace "erfrischend" with "aktualisiere".

**Comment by itprojects** [comment]
Thank you for noticing the translation error. There are many more such errors.

Can you look over the file `values-de/strings.xml` and see what other changes could be made?

Then post the new `strings.xml` here. This way we can reduce the number of necessary updates.

**Comment by agschaid** [comment]
I am sorry but I doubt that I'll find the time to do so. If I DO, I will merge a propper MR.

**Comment by itprojects** [comment]
If you don't have the time - don't worry about it at all.

If you do have the time, do _NOT_ do it the MR way, since that will cause problems.

**Comment by itprojects** [comment]
Translation updated in v7.0
