### ISSUE TITLE
PGP Support

### ISSUE THREAD

**Issue by craftyguy** [itprojects/InboxPager#5]
any plans to support email signing and encryption/decryption with pgp?

**Comment by itprojects** [comment]
Plans? Yes. Reality - not any time soon. Could be a long wait. In fact what you seem to be referring to is actually called S/MIME, which encrypts all but the recipients.

More info:

https://en.wikipedia.org/wiki/S/MIME

https://tools.ietf.org/html/rfc3156

**Comment by rgh36167** [comment]
Regarding PGP vs S/MIME - the later may be nicer in theory but never worked for me and my perception is that I get 100 times more email using PGP than S/MIME.

**Comment by itprojects** [comment]
Yes, you're right - PGP support should be prioritized.

PGP may be possible through:

https://www.openkeychain.org

**Comment by rgh36167** [comment]
So far I am using APG & k9mail - https://f-droid.org/repository/browse/?fdfilter=PGP&fdid=org.thialfihar.android.apg

**Comment by itprojects** [comment]
Popular combination. APG's GitHub page is apparently a OpenKeychain repo.
Are you a developer or just a casual user?

**Comment by rgh36167** [comment]
https://www.openkeychain.org/faq/#what-is-the-relationship-between-apg-and-openkeychain
I was under the impression that OpenKeychain is pretty much a complete reimplementation.

That README seems to be an accident from cloning repos.

In any case the 2 should be near perfectly API compatible from the perspective of an email client trying to use them.

**Comment by itprojects** [comment]
OpenKeychain is the right way forward, however it require some research, this is going to take some time.
