### ISSUE TITLE
Wrong gradle files

### ISSUE THREAD

**Issue by krt16s** [itprojects/InboxPager#7]
Looks like your gradle files are messed up, InboxPager/build.gradle and build.gradle are the same. The later however is for the root project and should contain the buildscript section.. something like:

````
buildscript {
    repositories {
        jcenter()
    }   
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'
    }   
}

allprojects {
    repositories {
        jcenter()
    }   
}
````

Also note that you have mismatching version information (version "1" and "1.0" are not the same) and you minsdk differs.

**Comment by itprojects** [comment]
Correct -> Corrected.

**Comment by krt16s** [comment]
Btw: Could you stop force-pushing and rewriting history? Whats the point of a version control if you remove the backlog all the time (and thus making any operations based on old commits dysfunctional)?

**Comment by itprojects** [comment]
Real version control requires real versions, in the first place. If the algorithm wasn't changed, then is it a version? No, it's like a typo - it's an involuntary error, and not much is lost, if any, in code development history. The problems with the old commits, should now be over, let's call it "app initialization on the repository". Your advice is taken, and appreciated!
