### ISSUE TITLE
problem fetching from gmail

### ISSUE THREAD

**Issue by zabbal** [itprojects/InboxPager#9]
Hmm, I was too optimistic when in #8 I've mentioned that it works with gmail. It does start fetching messages and even fetches few of them but eventually fails with:
Problem
length+69; index=70
...
and then java stack trace for Java.lang.String:579

The same inbox works with k9mail.

The issue is permanent - if I try again it immediately stuck on the 1st message so it seems like some message in my inbox somehow breaks InboxPager but I'm not sure how to determine which one it is to manually inspect for anomalies using thunderbird or smth else.

**Comment by itprojects** [comment]
InboxPager DOES work with gmail.

It most likely is the case that one of your messages are not handled correctly, somehow.

Can you repeat the error and write down the full stack trace?

When you've recorded the stack trace, also (if possible) can you share any of the following:
-have you received emails from this sender before? (compare)
-file size when you download the email from a web browser
-number of attachments
-is the message the last one, or should there be others after it
-anything in the email that doesn't seem right, is it empty, or too large, or html

After that you can manually move the message to a different folder(label) from gmail web interface, this should make the error disappear. Does it?
